    name: Build Container

    on: [push]

    jobs: 
      build-container: 
        runs-on: ubuntu-latest

        steps: 
          - uses: actions/checkout@v2

          - name: Build Container Image 
            run: docker build --tag helmo_pasi_labo910 .

          - name: Push Container Image 
            run: docker push helmo_pasi_labo910
